#端口
server:
 port: 8080

#数据库连接
spring:
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  password: admin
  url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=UTF-8&serverTimezone=UTC
  username: root

#xml地址
#mybatis.mapper-locations=classpath:mapper/*.xml

#mybatis-plus
mybatis-plus:
 configuration:
  map-underscore-to-camel-case: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 mapper-locations: classpath:mapper/*.xml